bark/bark/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

from views import views, regviews

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'bark.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^admin/', include(admin.site.urls)),

                       # #PROJECT URLS
                       # #----------
                       #
                       #Main Application Root
                       url(r'^$', views.index, name = 'index'),
                       # #BARK URLS
                       # #----------
                       #
                       # About page
                       url(r'^about/', views.about, name = 'about'),
                       #
                       #
                       # #Generic Post list
                       # Search with tags after, seperated by slashes
                       url(r'^barks/(.*)$', views.viewPosts, name = 'view_posts'),

                       #User Profile View
                       url(r'^users/(.*)', views.userprofile, name="user_profile"),
                       #
                       # #Specific Bark view
                       url(r'^bark/(?P<post_id>[\w-]+)/(?P<post_slug>[\w-]+)/', views.viewPost, name='view_post'),
                       #
                       # #Add new Bark
                       url(r'^new/(.*)?$', views.addPost, name = 'add_post'),
                       #
                       # #Search
                       # #Followed by query string or some form of search regex
                       url(r'^search/', views.search, name = 'search'),

                       url(r'^like_post/$', views.like_post, name='like_post'),
                       url(r'^like_comment/$', views.like_comment, name='like_comment'),
                       #
                       url(r'^follow/(.*)', views.follow_tag, name='follow_tag'),
                       url(r'^unfollow/(.*)', views.unfollow_tag, name='unfollow_tag'),
                       # #REGISTRATION VIEWS
                       # #---------
                       #
                       url(r'^signup/', regviews.signup, name = 'signup'),
                       url(r'^signin/', regviews.signin, name = 'signin'),
                       url(r'^signout/', regviews.signout, name = 'signout'),
                       #
                       url(r'^password-change/', regviews.passwordChange, name = 'passwordChange'),
                       url(r'^password-reset/', regviews.passwordReset, name = 'passwordReset'),
                       url(r'^password-reset-do/', regviews.passwordResetCode, name='passwordResetCode'),

                       url(r'^update-profile/', regviews.profileUpdate, name='profile'),
                       )

# Temp bit for uploading profile images during development
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
         'serve',
         {'document_root': settings.MEDIA_ROOT}))

bark/bark/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.core.validators import MinValueValidator

import random


# User Models

class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True)
    followed_tags = models.ManyToManyField('Tag', through="TagFollowing")

    profile_picture = models.ImageField(upload_to='profile_images', editable=True, default="profile_images/Bone.png")

    user_tag = models.OneToOneField('UserTag', related_name="userprofile_user_tag", editable=False)
    institution_tag = models.ForeignKey('InstitutionTag', related_name='userprofile_institution_tag', editable=False)

    def can_post_to_inst_tag(self, instTag):
        # Checks if a user can post to an InstitutionTag
        return instTag == self.institution_tag

    def save(self, *args, **kwargs):
        institution = getInstitution(self.user.email)

        # Automatically add user tag and institution tag to the user
        self.user_tag = UserTag.objects.get_or_create(name=self.user.username)[0]
        self.institution_tag = InstitutionTag.objects.get_or_create(name=institution)[0]
        super(UserProfile, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.user.username


class UserReset(models.Model):
    username = models.CharField(max_length=100)
    code = models.IntegerField(blank=False, default=999999)

    def __unicode__(self):
        return str(self.code)


# Comment Models

class Comment(models.Model):
    author = models.ForeignKey('UserProfile')
    post = models.ForeignKey('Post')
    creation_date = models.DateTimeField(auto_now_add=True)

    content = models.TextField()

    def __unicode__(self):
        return self.content


# Like Models

class Like(models.Model):
    author = models.ForeignKey('UserProfile')
    creation_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return str(self.author)

    class Meta:
        abstract = True


class PostLike(Like):
    post = models.ForeignKey('Post')

    def __unicode__(self):
        return str(self.author) + " liked " + str(self.post)

    class Meta:
        # Prevent a user from liking a post twice
        unique_together = ('author', 'post',)


class CommentLike(Like):
    comment = models.ForeignKey('Comment')

    def __unicode__(self):
        return str(self.author) + " liked " + str(self.comment)

    class Meta:
        # Prevent a user from liking a comment twice
        unique_together = ('author', 'comment',)


# Post Models

class Post(models.Model):
    author = models.ForeignKey('UserProfile')
    creation_date = models.DateTimeField(auto_now_add=True)
    views = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0)])
    tags = models.ManyToManyField('Tag', through="PostTagging", null=False, blank=False)
    rating = models.FloatField(default=0)

    title = models.CharField(max_length=100)
    content = models.TextField()

    slug = models.SlugField(editable=False)
    anonymous = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

        # Tag the user automatically
        if not self.anonymous:
            PostTagging.objects.get_or_create(post=self, tag=self.author.user_tag)
        else:
            anonymousTag = Tag.objects.get_or_create(name='anonymous')[0]
            PostTagging.objects.get_or_create(post=self, tag=anonymousTag)

    def __unicode__(self):
        return self.title

# Tag Models

class PostTagging(models.Model):
    post = models.ForeignKey('Post')
    tag = models.ForeignKey('Tag')
    tagging_date = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField(unique=True, max_length=30)
    creation_date = models.DateTimeField(auto_now_add=True)
    followers = models.ManyToManyField('UserProfile', through="TagFollowing", null=True)
    posts = models.ManyToManyField('Post', through="PostTagging", null=True)
    description = models.TextField(blank=True)
    slug = models.SlugField(editable=False)

    def save(self, *args, **kwargs):
        self.name = self.name.lower()
        self.slug = slugify(self.name)

        # Custom arg, that if we've updated the description, it's not given a default one...
        update = kwargs.pop('update', None)
        if not update:
            self.genDescription()

        super(Tag, self).save(*args, **kwargs)

    def genDescription(self):
        self.description = "This is for discussing @" + self.name + "."


    def __unicode__(self):
        return self.name


class InstitutionTag(Tag):
    def genDescription(self):
        self.description = "Posting in this tag is restricted to @" + self.name + " students."


class UserTag(Tag):
    def genDescription(self):
        self.description = "This tag lists the posts of @" + self.name + "."


class TagFollowing(models.Model):
    user = models.ForeignKey('UserProfile')
    tag = models.ForeignKey('Tag')
    follow_date = models.DateTimeField(auto_now_add=True)


# Misc. Functions
def getInstitution(email):
    # Could be changed to return domain.ac.uk instead of *.ac.uk
    return email.split("@")[1]

bark/bark/forms.py
from django import forms
from django.contrib.auth.models import User
from bark.models import UserProfile, Post, UserReset, Comment, getInstitution, Tag

# get data for user when they sign up
class UserForm(forms.ModelForm):
    username = forms.CharField(label="username")
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    # required to check if the user has an ac.uk domain
    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        domain = getInstitution(self.cleaned_data.get('email'))

        try:
            foundExistingTag = Tag.objects.get(name__iexact = username)

            raise forms.ValidationError("There is already a tag with the same name.")
        except Tag.DoesNotExist:
            pass

        #Checking email that it's a proper ac.uk email
        if "ac.uk" not in domain:
            print "Invalid Education domain."
            self.add_error('email', "Invalid institution email given. You'll need one with .ac.uk to signup with bark.")

# get data for the User Profile
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_picture',)

class PostForm(forms.ModelForm):
    class Meta:
        # provide an association between PostForm and Post.
        model = Post
        exclude = ('slug', 'views', 'author', 'creation_date', 'rating', 'tags')

        def form_valid(self, form):
            form.instance.author = self.request.user
            return super(Meta, self).form_valid(form)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('author', 'post')


# login Form (as name suggests)
class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=50, required=True)
    password = forms.CharField(label='Password', max_length=50, widget=forms.PasswordInput(), required=True)

    def clean(self):

        #Checking the existance of the username and password
        cleaned_data = super(LoginForm, self).clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")

        #Verify the details of the account
        try:
            user = User.objects.get(username=username)
            if not user.check_password(password):
                self.add_error('password', "Password invalid")
        except:
            self.add_error('username', "Invalid Username and Password")
            self.add_error('password', "Invalid Username and Password")
            return

# Shows the form for users requesting a reset code
# Checks the data they enter is valid
class PasswordResetForm1(forms.Form):
    username = forms.CharField(label='Username', max_length=50, required=True)
    email = forms.EmailField(label='Account Email', max_length=50, required=True)

    def clean(self):
        cleaned_data = super(PasswordResetForm1, self).clean()
        username = cleaned_data.get("username")
        email = cleaned_data.get("email")

        #Check the user exists
        try:
            user = User.objects.get(username=username)
        except:
            self.add_error('username', 'No account with that Username found.')
            self.add_error('email','')
            return

        #Check the emails match before sending a code
        if user.email != email:
            self.add_error('email', 'Account email is incorrect.')

# Shows form to users for resetting password
# Performs a lot of the validation
class PasswordResetForm2(forms.Form):
    username = forms.CharField(label='Username', max_length=50, required=True)
    code = forms.CharField(label='Reset Code', required=True)
    new_pass1 = forms.CharField(label='New Password', max_length=50, widget=forms.PasswordInput(), required=True)
    new_pass2 = forms.CharField(label='New Password (Again)', max_length=50, widget=forms.PasswordInput(), required=True)


    def clean(self):
        cleaned_data = super(PasswordResetForm2, self).clean()
        username = cleaned_data.get('username')
        code = cleaned_data.get('code')
        new_pass1 = cleaned_data.get('new_pass1')
        new_pass2 = cleaned_data.get('new_pass2')


        #Make sure the User exists
        try:
            user = User.objects.get(username=username)
        except:
            self.add_error('username', 'No account with that Username found.')
            return

        #Make sure they have requested a reset code
        try:
            userCode = UserReset.objects.get(username=username)
        except:
            self.add_error('username', 'Given username has not requested a code. If you require one, click the link at the top of the page.')
            return

        #Catching malformed codes, if they are strings or floats
        try:
            icode = int(code)
        except:
            self.add_error('code', 'Reset code must be a number')
            return

        #Making sure the code is correct and the new password is correct
        if userCode.code != icode:
            self.add_error('code', 'Reset code is invalid.')

        if new_pass1 != new_pass2:
            self.add_error('new_pass1', "Passwords didn't match")
            self.add_error('new_pass2', "Passwords didn't match")

# Allows user to change their password
# On creation MUST be passed with request=request as for cleaning.
class PasswordChangeForm(forms.Form):
    old_pass = forms.CharField(label='Old Password', max_length=50, widget=forms.PasswordInput(), required=True)
    new_pass1 = forms.CharField(label='New Password', max_length=50, widget=forms.PasswordInput(), required=True)
    new_pass2 = forms.CharField(label='New Password (Again)', max_length=50, widget=forms.PasswordInput(), required=True)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(PasswordChangeForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(PasswordChangeForm, self).clean()
        old_pass = cleaned_data.get('old_pass')
        new_pass1 = cleaned_data.get('new_pass1')
        new_pass2 = cleaned_data.get('new_pass2')

        #Check existing password is correct
        if not self.request.user.check_password(old_pass):
            self.add_error('old_pass', "Your current password is incorrect")

        #Check the new passwords are equal
        if new_pass1 != new_pass2:
            self.add_error('new_pass1', "Your passwords didn't match.")
            self.add_error('new_pass2', "Your passwords didn't match.")

class UserProfileUpdateForm(forms.Form):
    profile_picture = forms.ImageField(label='Profile Picture', required=False)
    bio = forms.CharField(label='About Me', initial='All about you', widget=forms.Textarea())

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UserProfileUpdateForm, self).__init__(*args, **kwargs)

bark/templates/bark/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}About{% endblock %}

{% block body_block %}

<div class="page-header">
    <h1>Bark!</h1>
</div>

<div>
    <b>Bark!</b> is our WAD2 team's <i>pet</i> project, a student-friendly discussion board.
    <br />
    <br />
    <p>
        It's quite simple, you can search the board if you have a question or <i>sniff around</i> by tags, and if you can't <i>retrieve</i>
        an answer then just BARK!
        You can also comment.
        <br />
        <br />
        If you have any questions you can <i>hound us</i> <a href="https://github.com/projectgoav/studeso">on GitHub</a>,
        or just make a post with your problem and we'll see it! Alternatively, if you <i>dig</i> it, please also let us know!
    </p>

    <img height="100" width="100" src="{% static 'images/akita_collar.png' %}" alt="The bark mascot wearing a collar"/>
    <br />
    projectgoav<br />
    2085749D<br />
    SCOTPAUL<br />
    mmckay99<br />
    <br />
    <i>N-Tier the Matrix</i>
</div>

{% block js %}
{% include "helpscript.html" with help_url="json/about.json" %}
{% endblock %}


{% endblock %}

bark/templates/bark/addPost.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load markdown_deux_tags %}

{% block script %}
    <link href="{% static 'taggle/assets/css/taggle.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/add_post.css' %}" rel="stylesheet"/>
{% endblock %}
{% block title %}Add a Bark!{% endblock %}

{% block body_block %}
<h2>Add a Bark!</h2>

    <div class="panel panel-default">
        <div class="panel-body">
            <form id="post_form" method="post" action="{% url 'add_post' '' %}">
                {% csrf_token %}
                {% bootstrap_field form.title %}
                {% bootstrap_field form.content %}
                {% markdown_allowed %}
                {% bootstrap_field form.anonymous %}
                <div class="form-group">
                    <label class="control-label" for="tags">Tags</label>
                    <div class="input textarea clearfix" id="tags"></div>
                </div>

                <input class="btn btn-primary" type="submit" name="submit" value="Create New Bark!" />
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}
{% include "helpscript.html" with help_url="json/addpost.json" %}
<!-- This script creates the JS variable "defaultTagList", which is used in
    as the default value in the Taggle text entry -->
<script type="text/javascript">
    var defaultTagList = {{ defaultTagList | safe }}
</script>

<script src="{% static 'js/add_post.js' %}"></script>
<script src="{% static 'taggle/assets/js/taggle.min.js' %}"></script>
{% endblock %}

bark/templates/bark/index.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}
{% load postlist %}

{% block body_block %}

{% if user.is_authenticated %}
  <h2 id="help-3">Welcome back to Bark, {{ user.username }}!</h2>
{% else %}
  <h2 id="help-3">Welcome to Bark! <small> A student Q&amp;A discussion site</small></h2>
{% endif %}

<h4 id="help-5"> Here are the newest, coolest Barks {% if user.is_authenticated %}from tags you follow!{% else %}out there right now!{% endif %}</h4>
  <span id="help-6"></span>
  {% csrf_token %}
  <form class="input-block-level" action="{% url 'add_post' '' %}">
      <div class="form-group">
          <label for="new_bark_btn">Can't find it?</label>
          <button type="submit" class="btn btn-default btn-warning" id="new_bark_btn">Bark about it!</button>
      </div>
    </form>

<div id="help-4">
    {% for topPost in topPosts %}
      {% get_view topPost %}
    {% endfor %}
</div>
    {% if topPosts.has_other_pages %}
        {% bootstrap_pagination topPosts %}
    {% endif %}
<br />

<!-- If there are no top posts, i.e. if the user hasn't followed any tags -->
{% if topPosts|length == 0 %}
<h2>You aren't following any tags!<br /><br /><b>Use the sidebar on the left to get started!</b></h2>
{% endif %}
{% endblock %}

{% block js %}
  {% if user.is_authenticated %}
    {% include "helpscript.html" with help_url="json/indexA.json" %}
  {% else %}
    {% include "helpscript.html" with help_url="json/index.json" %}
  {% endif %}
{% endblock %}

bark/templates/bark/postformat.html
{% load staticfiles %}
{% load markdown_deux_tags %}
<div class="panel panel-default">
  <div class="panel-heading"><h3 class="panel-title"><a href="{% url 'view_post' post.id post.slug %}">{{ post.title|truncatechars:50 }}</a><small class="num-likes pull-right">{{ post_likes }} found this interesting</small></h3></div>
  <div class="panel-body">{{ post.content|markdown|truncatewords_html:150 }}</div>
  <div class="panel-footer bark-tags">
    <b>Tags: </b>
        {% if not post.anonymous %}
                <a class="user" href={% url 'user_profile' post.author.user_tag %}>@{{ post.author.user_tag }}</a>
        {% endif %}
        {% if post_inst_tag %}
                <span> | </span><a class="inst" href={% url 'view_posts' post_inst_tag %}>@{{ post_inst_tag }}</a>
            {% endif %}
            {% for post_tag in post_tags %}
                <span> | </span><a class="tag" href={% url 'view_posts' post_tag %} >@{{ post_tag }}</a>
            {% endfor %}
    </div>
  </div>

bark/templates/bark/postlist.html
{% extends 'base.html' %}
{% load postlist %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block title %}{{ tags.0.name }}...{% endblock %}

{% block body_block %}
<h2>Tag{{ tags|pluralize }}:</h2>
<div class="row" id="TAGS">
    {% for tag in tags %}

    <div class="col-sm-6">
        <h3>{{ tag.name }}</h3>

        {% buttons %}
        {% if not tag.followed_by_user %}
            <a href="{% url 'follow_tag' tag %}"><button class="btn btn-primary" id="follow_tag">Follow This Tag</button></a>
        {% else %}
            <a href="{% url 'unfollow_tag' tag %}"><button class="btn btn-primary" id="unfollow_tag">Unfollow This Tag</button></a>
        {% endif %}
            <a href="{% url 'add_post' tag %}"><button class="btn btn-warning" id="new_bark_with_tag">Bark with Tag</button></a>
       {% endbuttons %}
    </div>
    {% endfor %}
</div>
<br />
    {% for post in posts %}
    {% get_view post %}
    {% endfor %}
    {% if posts.has_other_pages %}
        {% bootstrap_pagination posts %}
    {% endif %}
{% endblock %}

{% block js %}
{% include "helpscript.html" with help_url="json/posts.json" %}
{% endblock %}

bark/templates/bark/postview.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load markdown_deux_tags %}

{% block js %}
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/like.js' %}"></script>
{% include "helpscript.html" with help_url="json/post.json" %}
{% endblock %}

{% block title %}{{ post.title }}{% endblock %}

{% block body_block %}
{% if post %}
    <h2 id="pHEAD" class="page-header col-sm-10">{{ post.title }}
        <small>
            views: {{ post.views }}, <span class="post-like-num">{{ post_likes }}</span> found this interesting
        </small>
    </h2>

    <div class="col-sm-10">
    <div class="panel panel-primary">
        <div class="small panel-heading" id="tiime">{{ post.creation_date }}</div>
        <div class="panel-body">{{ post.content|markdown }}</div>
        <div class="panel-footer bark-tags" id="tHEAD">
            <b>Tags: </b>
            {% if not post.anonymous %}
                <a class="user" href={% url 'user_profile' post.author.user_tag %}>@{{ post.author.user_tag }}</a>
            {% endif %}

            {% if post_inst_tag %}
            <span> | </span>
            <a class="inst" href={% url 'view_posts' post_inst_tag %}>@{{ post_inst_tag }}</a>
            {% endif %}
            {% for post_tag in post_tags %}
            <span> | </span>
            <a class="tag" href={% url 'view_posts' post_tag %} >@{{ post_tag }}</a>
            {% endfor %}

        {% if user.is_authenticated %}
            {% csrf_token %}
                <div class="pull-right" id="post-like">
                {% buttons %}
                    <button class="like-post-btn" type="submit">
                        {% if post_liked %}
                            {% bootstrap_icon "ok" %}
                        {% else %}
                            {% bootstrap_icon "thumbs-up" %}
                        {% endif %}
                    </button>
                {% endbuttons %}
                </div>
        {% endif %}

        </div>
    </div>
    <h3 class="page-header" id="cHEAD">Comments ({{ post.comment_set.all|length }})</h3>

    {% for comment in comments %}
        <div class="panel panel-default">
            <div class="small panel-heading">{{ comment.creation_date }}<span class="pull-right small"><span class="comment-like-counter-{{ forloop.counter }}">{{ comment.commentlike_set.all|length }}</span> found this helpful</span></div>
            <div class="panel-body">{{ comment.content|markdown }}</div>
            <div class="panel-footer bark-tags">
                <a href={% url 'user_profile' comment.author %} class="user">@{{ comment.author }}</a>
                        <div class="pull-right small">
                        {% if user.is_authenticated %}
                            {% buttons %}
                                <button class="comment-like comment-like-{{ forloop.counter }} like-btn" type="submit">
                                    {% if comment.liked_by_user %}
                                        {% bootstrap_icon "ok" %}
                                    {% else %}
                                        {% bootstrap_icon "thumbs-up" %}
                                    {% endif %}
                                </button>
                            {% endbuttons %}
                        {% endif %}
                        </div>
            </div>
        </div>
    {% endfor %}

    {% if user.is_authenticated %}
        <form id="comment_form" method="post" action=".">
            {% csrf_token %}
            <div class="panel panel-primary">
                <div class="panel-heading"><h3 class="panel-title">Add a comment</h3></div>
                <div class="panel-body">
                    <div class="form-group">
                        {% markdown_allowed %}
                        <textarea id="id_content" class="form-control" rows="4" required="required" placeholder="Comment here..." name="content" cols="40"></textarea>
                    </div>
                    <input class="btn btn-primary" type="submit" name="submit" value="Add Comment" />
                </div>
            </div>
        </form>
    {% endif %}

  </div>

{% else %}
    <h2>No post exists!</h2>
{% endif %}
{% endblock %}

bark/templates/bark/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load postlist %}

{% block title %}User Profile :  {{ username }}{% endblock %}

{% block body_block %}

<span class="help-s1"></span>

{% if NOT_FOUND %}
<h1> Username Not Found </h1>

<p> A user with the given username was not found. Please try your search again!</p>
{% else %}

  <h1>{{ username }}'s Profile</h1>
  <div class="col-sm-10">
  <div class="panel panel-default help-s2">
      <div class="panel-body">
      <div class="row">
        <div class="col-sm-5">
          <img src="{{ MEDIA_URL }}{{ img }}" class="img-responsive" alt="User's Profile Image" />
        </div>
        <div class="col-sm-5">
          {{ bio }}
        </div>
      </div>
      {% if current %}
        <h3 class="page-heading help-s3"> Account Options </h3>
        <div class="row">
          <div class="col-sm-5">
            <p><a href="{% url 'passwordChange' %}">Change Password</a></p>
          </div>
          <div class="col-sm-5">
            <p><a href="{% url 'profile' %}">Update Profile</a></p>
          </div>
        </div>
      {% endif %}
    </div>
      <div class="panel-footer bark-tags">
          <b>Total Barks:</b> {{ bark_count }} | <span class="text-muted">Post Likes: {{ post_likes }} | Comment Likes: {{ comment_likes }}</span>
      <div class="pull-right">
        <b>Total Bark Views: </b> {{ bark_views }}
      </div>
    </div>
  </div>
  <br>
  <h2 class="page-heading"> Posts by User <small><a href="{% url 'view_posts' usertag %}">See more...</a></small></h2>
  {% if posts %}
    {% for p in posts %}
      {% get_view p %}
    {% endfor %}
  {% else %}
  <p class="text-muted">This user has not made any posts</p>
  {% endif %}
{% endif %}
</div>
{% endblock %}

{% block js %}
{% include "helpscript.html" with help_url="json/profile.json" %}
{% endblock %}

bark/templates/bark/search.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Search - {{ query }} {% endblock %}

{% block body_block %}
{% load postlist %}

{% if posts %}
<h2 id="head">Results for "{{ query }}"</h2>
{% if tags %}
    <h4>
    <br>Related tags:

    {% for tag in tags %}
        <b><a href={% url 'view_posts' tag.name %}>{{ tag.name }}</a></b>  <a href={% url 'follow_tag' tag.name %}>(follow)</a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
    </h4>
{% else %}
    <h4>No related tags found for "{{ query }}"</h4>
{% endif %}
<br>
<br>
<div>
    {% for post in posts %}
        {% get_view post %}
    {% endfor %}
</div>


{% else %}
<h2 id="head">Oh shit-h tzu, no results for "{{ query }}"!</h2>
<br>
<h3>
<i><a href="{% url 'add_post' '' %}">Why not Bark about it?</a></i>
</h3>
{% endif %}
{% endblock %}

{% block js %}
{% include "helpscript.html" with help_url="json/search.json" %}
{% endblock %}